on:
  push:
    branches:
    - master
    - main
    
name: Deploy to Netlify
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Publish
      uses: actions/setup-node@v3
      with:
         node-version: 16
    - env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
           npm install
           npm install netlify-cli --save-dev
           export OUTPUT=$(sh -c "netlify deploy --build --dir=.next")
           export NETLIFY_OUTPUT=$(echo "$OUTPUT")
           export NETLIFY_URL=$(echo "$OUTPUT" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*(--)[a-zA-Z0-9./?=_-]*') #Unique key: --
           export NETLIFY_LOGS_URL=$(echo "$OUTPUT" | grep -Eo '(http|https)://app.netlify.com/[a-zA-Z0-9./?=_-]*') #Unique key: app.netlify.com
           export NETLIFY_LIVE_URL=$(echo "$OUTPUT" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*' | grep -Eov "netlify.com") #Unique key: don't containr -- and app.netlify.com
           echo "::set-output name=NETLIFY_OUTPUT::$NETLIFY_OUTPUT"
           echo "::set-output name=NETLIFY_URL::$NETLIFY_URL"
           echo "::set-output name=NETLIFY_LOGS_URL::$NETLIFY_LOGS_URL"
           echo "::set-output name=NETLIFY_LIVE_URL::$NETLIFY_LIVE_URL"
           echo "NETLIFY_LIVE_URL::$NETLIFY_LIVE_URL"
